### ISSUE TITLE
E621dl Crash

### ISSUE THREAD

**Issue by shadydeath** [wwyaiykycnf/e621dl#27]
D:\Program Files (x86)\e621dl>e621dl.exe
e621dl      INFO     running e621dl version 2.4.6
e621dl      INFO     e621dl was last run on 2001-01-01
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27
, in <module>
  File "../e621dl.py", line 93, in <module>
  File "../lib\e621_api.py", line 30, in get_posts
TypeError: string indices must be integers

**Comment by wwyaiykycnf** [comment]
Hello,
Sorry this error is occurring.  Please follow the [bug reporting process]( https://github.com/wwyaiykycnf/e621dl/blob/master/docs/reporting_bugs.md) so that I have the required information to address this.  Feel free to use an anonymous email address to send the information from if you like.

I suspect this is a problem with your config file or tags file, but following the [bug reporting process]( https://github.com/wwyaiykycnf/e621dl/blob/master/docs/reporting_bugs.md) will allow me to confirm this.  If it is indeed a problem with e621dl, I may not be able to fix it for... some weeks.
