### ISSUE TITLE
Init Problem

### ISSUE THREAD

**Issue by BurningPixels** [wwyaiykycnf/e621dl#34]
When i'm try to init the program i get that

`
C:\Program Files (x86)\e621dl>e621dl.exe
e621dl      INFO     running e621dl version 2.4.6
configfile  ERROR    new default file created: config.txt
configfile  ERROR       verify this file and re-run the program
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "../e621dl.py", line 44, in <module>
  File "../lib\support.py", line 52, in get_configfile
  File "../lib\support.py", line 45, in make_default_configfile
IOError: [Errno 13] Permission denied: 'config.txt'
Drücken Sie eine beliebige Taste . . .`

i have python 3.6.0 and 2.7.13 installed. Can someone please help me?

**Comment by Wulfre** [comment]
You need to run the program as an administrator so that it can create files inside of the Program Files directory.

**Comment by DatDraggy** [comment]
This is pretty old but I guess it could help other people. I'm not exactly sure what it wants but delete the config file and re-run.

Could also be that it doesn't have enough permissions. Try running python as an administrator.
