### ISSUE TITLE
Downloader stopped working

### ISSUE THREAD

**Issue by ssz333** [wwyaiykycnf/e621dl#39]
I've been using this program for a while now, everything working without problem until last week - when i'm trying to run it, i'm getting 

http://i.imgur.com/r44Frgm.png

Haven't changed anything in software nor hardware. Anybody know how to fix this?

**Comment by Wulfre** [comment]
This was solved in issue #36. e621 blocked the user agent that wwyaiykycnf was using. DatDragy submitted pull #37 which should fix it up; Otherwise, my fork is still being actively worked on.

**Comment by ssz333** [comment]
Thanks for your answer

I've checked both links you posted and tried to fix it on my own - with no success, sadly. 
Since .pyc files doesn't seem to be openable, i've downloaded source version of e621dl by ww. Then i attempted to edit the .py files just like it said in #36 
http://i.imgur.com/BzITLut.png. Also tried without v and adding e621dl instead - same result, which is 
invalid syntax error - http://i.imgur.com/Rn8eN5m.png - and i have no idea how to fix it, yet again. Never seen anything other than .exe file before.

**Comment by Wulfre** [comment]
You should not replace `VERSION` with the actual version number. It is a variable that supplies the current version number to the program upon request.

My fork should not need any configuration other than picking your tags in the config file, but I won't go into great detail about my fork here since it wouldn't be appropriate and may be confusing to people who read this issue at a later time.

**Comment by AzureWaning** [comment]
I was having the same problem, I got the Python version, installed Python and changed the files according to #37 but now I don't know how to run the program (e621dl.py), if I run it directly it pops up and closes itself immediately. I have no idea of what I'm doing.

**Comment by DatDraggy** [comment]
Search for "IDLE". It's the python editor/ide.
Open it and then click on "File". There you go to open and simply open your e621dl.py file inside the e621dl directory. Then you press F5 (or go to Run > Run Module)

If you get any errors about syntax etc download python 2.7

**Comment by silveralf** [comment]
I have the same issue. Can anyone please help me with it (in human language please...)!

**Comment by DatDraggy** [comment]
Okay.
Go to https://www.python.org/ftp/python/2.7.13/python-2.7.13.msi and install python 2.7 if you dont already have it. Then open "IDLE (Python GUI)" (should find it by just typing it in your search bar). 
Download the e621 downloader from here https://github.com/wwyaiykycnf/e621dl/archive/v2.4.6.zip and unzip it.

Click on File and it should look like this: https://puu.sh/uBxX2/f2f04ed214.png
Now go to open and open the e621dl.py file. Minimize the new window and now go into the e621 directory with your windows explorer. Now go into "lib" so that you can see these files: https://puu.sh/uBy9o/45281dad42.png
Now you either just double click "version.py" and "downloader.py" or edit them with notepad. Now go to line 15 and replace `version = 'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.0.12) Gecko/20070731 Ubuntu/dapper-security Firefox/1.5.0.12'` with `version = 'e621dl ' + VERSION + ' (by putYourNameHere)'`

Then add from `lib.version import VERSION` below the last orange "import" text.

It's supposed to look like this: https://puu.sh/uByna/f5de1be2ed.png

Now save with ctrl+s and close both windows again. Open the first window (e621dl.py) and press F5.

Tell me if you need any more help

**Comment by silveralf** [comment]
Thank you so much for your detailed explanation man! Everything working fine now! kudos+++

**Comment by DatDraggy** [comment]
No problem :D Just recorded a video so that I can just send that to people lol.

**Comment by silveralf** [comment]
Nice!
There is a small mistake in your comment on this line:
'Now you either just double click "version.py" and "downloader.py" or edit them with notepad.'

I was suppose to edit downloader.py and SUPPORT.PY instead of VERSION.PY (i saw it thanks to your screenshot)!

**Comment by silveralf** [comment]
upd: I have pasted my old tags.txt and config.txt files and the download works perfect! Thanks again!

**Comment by DatDraggy** [comment]
Oops! Thanks for telling me xD

**Comment by AzureWaning** [comment]
Here's what I get when I try to run it:

Traceback (most recent call last):
  File "my e621.py location", line 93, in <module>
    current_page, default.MAX_RESULTS)
  File "my e621_api.py location", line 30, in get_posts
    uploads.append(UPLOAD(post['file_url'], post['md5'], post['file_ext']))
TypeError: string indices must be integers

**Comment by DatDraggy** [comment]
Can you send me a screenshot of your e621-master folder?

**Comment by Wulfre** [comment]
That error is for having more than 5 tags being searched for. wwyaiykycnf didnt code anything to catch it.

**Comment by DatDraggy** [comment]
Oh lol rip my error reading

**Comment by Cylias** [comment]
Has anyone been able to get this to work with the Mac version?

I edited the files as described and I've been using v2.7.13 of the python launcher, but I'm still getting the JSON error.

Is it a problem with the program trying to pull from a bad directory?

I've attached the error message below:

MyMacName:~ MyName$ cd '/Users/MyName/Desktop/e621dl-2.4.6/' && '/usr/bin/pythonw'  '/Users/MyName/Desktop/e621dl-2.4.6/e621dl.py'  && echo Exit status: $? && exit 1
e621dl      INFO     running e621dl version 2.4.6
e621dl      INFO     e621dl was last run on 2017-03-13
Traceback (most recent call last):
  File "/Users/MyName/Desktop/e621dl-2.4.6/e621dl.py", line 93, in <module>
    current_page, default.MAX_RESULTS)
  File "/Users/MyName/Desktop/e621dl-2.4.6/lib/e621_api.py", line 26, in get_posts
    results = loads(SPOOF.open(request).read().decode())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
MyMacName:e621dl-2.4.6 MyName$

**Comment by Cylias** [comment]
Has anyone here gotten the Mac version working? I followed all of the instructions with editing the files like you requested, but for some reason I am still getting the following error:

//

MyMacName:~ MyName$ cd '/Users/MyName/Desktop/e621dl-2.4.6/' && '/usr/bin/pythonw'  '/Users/MyName/Desktop/e621dl-2.4.6/e621dl.py'  && echo Exit status: $? && exit 1
e621dl      INFO     running e621dl version 2.4.6
e621dl      INFO     e621dl was last run on 2017-03-13
Traceback (most recent call last):
  File "/Users/MyName/Desktop/e621dl-2.4.6/e621dl.py", line 93, in <module>
    current_page, default.MAX_RESULTS)
  File "/Users/MyName/Desktop/e621dl-2.4.6/lib/e621_api.py", line 26, in get_posts
    results = loads(SPOOF.open(request).read().decode())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
MyMacName:e621dl-2.4.6 MyName$ 

//

**Comment by DatDraggy** [comment]
Try cd-ing in the dir first and then only type "python e621dl.py" in the terminal. I don't really have an idea what is not working. You sure you changed both user agents correctly? Can you show me the lines?

**Comment by BluBudgies** [comment]
Is there no way to have it use the same .cache, so I don't download all the files again? It crashes any time I try adding my old .cache. (I am assuming that is how it knows what images you already have.)
Also it seems the "part_used_as_name": "id", is not working.

**Comment by DatDraggy** [comment]
You should mess with the cache. Just leave it there. If you leave all the files in the downloads dir then it won't redownload them.

What do you mean with 

> Also it seems the "part_used_as_name": "id", is not working.

**Comment by BluBudgies** [comment]
Nevermind, I am stupid I used [https://github.com/wwyaiykycnf/e621dl/issues/33](33) I forgot I had that version. My bad.

**Comment by Cylias** [comment]
Sorry for the delay DatDraggy,

I CD'd into the directory and then did "python e621dl.py" and this is what the output was:

//

Traceback (most recent call last):
  File "e621dl.py", line 93, in <module>
    current_page, default.MAX_RESULTS)
  File "/Users/MyName/Desktop/e621dl-2.4.6/lib/e621_api.py", line 26, in get_posts
    results = loads(SPOOF.open(request).read().decode())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
MyMacName:e621dl-2.4.6 MyName$ 

//

Any ideas?

**Comment by Cylias** [comment]
So, quick update, I downloaded the master .zip from here: https://github.com/wwyaiykycnf/e621dl/archive/master.zip

So, it works with any combination of tags, but once I change the "last run" date on the "config.txt" file, I get the error above. I can change any other part of the config file, but if I change the date at all I get that error.

**Comment by DatDraggy** [comment]
If you download the newest version from the newest release then everything should work after changing the user agent. What are you exactly trying to change it to? Maybe its just the wrong format becaude thats the only reason I can think off

**Comment by Cylias** [comment]
So, weirdly enough, I fixed the date issue by changing the file "default.py" in the "lib" folder.

On line 6, I edited the following:

//

DATETIME_FMT = "%Y-%m-%d"

↓

DATETIME_FMT = "**%y**-%m-%d"

//

I'm not 100% sure why this works, but it does.

**Comment by Godwrath1** [comment]
Any idea why I keep getting the error message "missing parentheses in call to 'print'" on line 145  both with the original scripts and with the edited ones?

**Comment by DatDraggy** [comment]
I think you are using the wrong python version. You need 2.7 to run it ^^ Python 3 has a different syntax.

**Comment by Godwrath1** [comment]
Yeah. I figured that out and was just going to come and delete my comment before someone realized I was being a derp.  I was using 3.4.   Seems everything is running right now.
