### ISSUE TITLE
Not working - Value Error, no JSON object could be decoded

### ISSUE THREAD

**Issue by lylatveteran** [wwyaiykycnf/e621dl#51]
I don't know if you even still work on this, but this was the most awesome tool ever when it worked. Nowadays, this message is all I get when I try to start it.
I double click on the Run_e621dl_In_Windows file, like the instructions say to
I've also attempted to change the last-used-by date like what was suggested, but nothing seems to work.

Any info would be helpful

**Comment by BluBudgies** [comment]
> I don't know if you even still work on this, but this was the most awesome tool ever when it worked. Nowadays, this message is all I get when I try to start it.
> I double click on the Run_e621dl_In_Windows file, like the instructions say to
> I've also attempted to change the last-used-by date like what was suggested, but nothing seems to work.
> 
> Any info would be helpful

You need to add a minimum of 1 tag.

**Comment by lylatveteran** [comment]
I have. And I've tried using other tags as well. Maybe it has to do with the way they are added?

For example, I tested out a tag: Arbok and put it in the tags file like this...

# Instructions:
#
# Add tags/artists to download to this file, one group per line.  Any tag
# combination that works on the web site will work here, including all the
# meta-tags (see https://e621.net/help/cheatsheet for more information on
# tags and meta-tags).
#
# NOTE: All lines in this file that begin with # are treated as comments and
# are ignored by e621dl
#
# Each line in this file will be treated as a separate group, and a new folder
# inside the downloads directory will be created for each line in this file.
#
# List any tags, artists, meta-tags, or groups of tags you would like to
# track below:

Arbok

Maybe I'm not supposed to skip a line? Or is there another way I'm supposed to put it in?

________________________________

**Comment by Redtile** [comment]
I am also having the same issue 
e621dl      INFO     running e621dl version 2.4.6
e621dl      INFO     e621dl was last run on 2019-10-30
Traceback (most recent call last):
  File "e621dl.py", line 93, in <module>
    current_page, default.MAX_RESULTS)
  File "C:\Users\Luke\Downloads\e621dl-2.4.6\e621dl-2.4.6\lib\e621_api.py", line 26, in get_posts
    results = loads(SPOOF.open(request).read().decode())
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
I have tried adding tags with capital letters and lower case letters at the front and I have tried different spacings and adding commas in between tags but it doesn't seem to work any tips?

**Comment by DatDraggy** [comment]
Sup guys
Since nobody is maintaining this anymore, I'll ask @wwyaiykycnf if he wants to add me as a collaborator so that I can maintain it in the original repo and help you guys.

Atm I can't look into your problem because I can't test as I'm on vacation but I will be able to next week

**Comment by BluBudgies** [comment]
The last run config is how far back e621dl will look for posts. So I would recommend something like: 2007-1-1 to grab all the posts on newly added tags and then you can change it back to the current date.

**Comment by Redtile** [comment]
> The last run config is how far back e621dl will look for posts. So I would recommend something like: 2007-1-1 to grab all the posts on newly added tags and then you can change it back to the current date.

just tried this it didnt work and @DatDraggy that would be amazing I have been trying to find something like this for a while now and this is the closest I have come so far

**Comment by Redtile** [comment]
ok breif update, I fuggured out how to input tags they must be seperated with a return like so
Tag1
Tag2
ETC...
still getting the JSON error though and looking at the code I really cant tell whats wrong, will update further if I come across anything

**Comment by WispTheHusky** [comment]
Hey.

It may be because of the date format. It doesn't work on dates, but instead
on days. So, you'll want to put it as "4696" instead.

See if that sorts it for you.

-Wisp

**Comment by lylatveteran** [comment]
Thanks for all your help so far guys

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Redtile** [comment]
@WispTheHusky unfortunately that still doesn't work it now give the error of the config file being wrong and requiring the date format to be "YYYY-MM-DD" am I perhaps missing a file? it say it needs a JSON but I cant find any file in the folder that has a .json extension

**Comment by BluBudgies** [comment]
You may need to try the python method, I had some issues with the windows version myself.

**Comment by Redtile** [comment]
@BluBudgies how do I do that? I am currently running it in cmd as an admin Im not sure what you mean by the python method
